version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - npm ci
      - apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - echo "Configuring Cypress..."
      - npm run cy:setup
  build:
    commands:
      - echo "Running unit tests..."
      - npm run test:unit
      - echo "Running component tests..."
      - npm run test:component
      - echo "Running e2e tests..."
      - npm run test:e2e

artifacts:
  files:
    - '**/*'
  base-directory: out/

cache:
  paths:
    - ./node_modules/**/*
