version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - npm ci
      - apt-get install -y libatk1.0-0 libatk-bridge2.0-0 libcups2 libgtk-3-0 libgbm-dev

  build:
    commands:
      - echo "Running unit tests..."
      - npm run test:unit
      - echo "Running component tests..."
      - npm run test:component
      - echo "Running e2e tests..."
      - npm run test:e2e

artifacts:
  files:
    - '**/*'
  base-directory: out/

cache:
  paths:
    - ./node_modules/**/*
