version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - cd ./app
      - echo "Installing dependencies..."
      - npm ci
  build:
    commands:
      - echo "Building..."
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: app/out

cache:
  paths:
    - ./app/node_modules/**/*
