version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - cd ./app
      - echo "Installing dependencies..."
      - npm ci
  build:
    commands:
      - echo "Building..."
      - npm run build:next
      - |
        if [ $NEXT_PUBLIC_BUILD_ENVIRONMENT = "dev" ]; then
          npm run build:storybook && npm run postbuild:storybook;
        fi

artifacts:
  files:
    - '**/*'
  base-directory: app/out

cache:
  paths:
    - ./app/node_modules/**/*
