version: 0.2

phases:
  pre_build:
    commands:
      - cd ./app
      - echo "Installing dependencies..."
      - npm ci
  build:
    commands:
      - echo "Building..."
      - npm run build

artifacts:
  files:
    - out/**/*

cache:
  paths:
    - node_modules/**/*
