version: 0.2

phases:
  build:
    commands:
      - cd ./app
      - echo "Installing dependencies..."
      - npm ci
      - echo "Building..."
      - npm run build

artifacts:
  files:
    - ./app/out/**/*

cache:
  paths:
    - ./app/node_modules/**/*
