import 'normalize.css';
import '@/styles/global.scss';

import { AppAdmin } from '@/components/AppAdmin';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <>
          <AppAdmin />
          {children}
        </>
      </body>
    </html>
  );
}
